FileVersion = 1
Projects = {libtcc = {Path = "vendor/libtcc"}, raylib-beef = {Path = "vendor/raylib-beef/raylib-beef"}, "zen.tests" = {Path = "zen.tests"}, zen = {Path = "zen"}}

[Workspace]
StartupProject = "zen"

[Configs.Release.Win64]
LTOType = "None"

[Configs.Test.Win32]
ConfigSelections = {libtcc = {Config = "Debug"}}

[Configs.Test.Win64]
ConfigSelections = {libtcc = {Config = "Debug"}}
