FileVersion = 1
Dependencies = {corlib = "*", libtcc = "*", raylib-beef = "*"}

[Project]
Name = "zen"
StartupObject = "Zen.Program"
DefaultNamespace = "Zen"

[Configs.Debug.Win64]
DebugCommandArguments = "$(WorkspaceDir)/test/main.zen -wait"
