FileVersion = 1
Projects = {zen = {Path = "."}, libtcc = {Path = "vendor/libtcc"}, raylib-beef = {Path = "vendor/raylib-beef/raylib-beef"}}

[Workspace]
StartupProject = "zen"

[Configs.Release.Win64]
LTOType = "None"
